### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Awire9966**
Update ReadMe.md for those who need the binaries.

### CODE REVIEW

**Review by GoldenretriverYT — COMMENTED** [review]
We don't know if this contains malware. I'd say @IonelPopJara should maybe provide prebuilt binaries using the Releases section

**Comment by Awire9966** [comment]
> We don't know if this contains malware. I'd say @IonelPopJara should maybe provide prebuilt binaries using the Releases section

Dude i litterly provided a virus scan

**Comment by GoldenretriverYT** [comment]
> > We don't know if this contains malware. I'd say @IonelPopJara should maybe provide prebuilt binaries using the Releases section
> 
> Dude i litterly provided a virus scan

you know we can see you added it afterwards? also virus scans arent a 100% gurantee of it not containing a virus lol, virus scanners arent magic tools that will detect every virus as soon as they were developed

**Comment by Awire9966** [comment]
> > > We don't know if this contains malware. I'd say @IonelPopJara should maybe provide prebuilt binaries using the Releases section
> > 
> > 
> > Dude i litterly provided a virus scan
> 
> you know we can see you added it afterwards? also virus scans arent a 100% gurantee of it not containing a virus lol, virus scanners arent magic tools that will detect every virus as soon as they were developed

 I didnt realize i forgot to add it. I have had it since i put the file on my website

**Pull request closed without merging**
